# Generated by Django 5.0.6 on 2024-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('date_of_interview', models.DateField(max_length=20)),
                ('hour_of_interview', models.TimeField(max_length=20)),
                ('source', models.CharField(choices=[('מעוף', 'מעוף'), ('פייסבוק', 'פייסבוק'), ('JobMaster', 'JobMaster'), ('חמח הראל', 'חמח הראל'), ('עבודה עכשיו', 'עבודה עכשיו'), ('JobKarov', 'JobKarov'), ('אתר בזק אונליין', 'אתר בזק אונליין'), ('פייסבוק ממומן', 'פייסבוק ממומן'), ('חמח', 'חמח'), ('רון כהן', 'רון כהן')], max_length=500)),
                ('status', models.CharField(choices=[('זומן', 'זומן'), ('התקבל', 'התקבל'), ('לא התקבל', 'לא התקבל'), ('הסיר מועמדות', 'הסיר מועמדות'), ('פסל', 'פסל'), ('מבדק אמינות', 'מבדק אמינות'), ('קבט', 'קבט')], max_length=100)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
